### ISSUE TITLE
Prevent Overlap Logic Error

### ISSUE THREAD

**Issue by sptobey** [mbinsfeld/Tetrace#6]
There is a problem with the prevent overlap not working all of the time.  The preventOverlap script relies on the currentPiece static class to ensure that only the last selected piece will be moved (this I think is correct).  But, for some reason the parent tetris piece's revert method is not being called when a collision is detected.  I suspect i am not thinking about the logic correctly.  It may also help to look in Project Settings -> Physics -> Collision Matrix (at the bottom).

**Comment by mbinsfeld** [comment]
I'll take a look in the morning.

**Comment by mbinsfeld** [comment]
I know what the bug is. 
"isSelected" is only set to true on the gameObject that the player clicks on.
I can take care of solving this.

**Comment by mbinsfeld** [comment]
The problem was that we were only setting selected on the other gameObjects if the parent was the one clicked. I added this to the end and added a condition for wether or not isSelected needed to be set in the child loop:
else {
preventOverlap parentOverlapScript = transform.parent.GetComponent<preventOverlap> ();
parentOverlapScript.setSelected (isSelected);
}

**Comment by mbinsfeld** [comment]
Complete setSelected function for clarity:
public void setSelected(bool isSelected) {
		this.isSelected = isSelected;

		// Set children if any
		if (transform.parent == null) {
						foreach (Transform child in transform) {
								preventOverlap childOverlapScript = child.gameObject.GetComponent<preventOverlap> ();
								if(childOverlapScript.getSelected() != isSelected)
									childOverlapScript.setSelected (isSelected);
						}
				} else {
						preventOverlap parentOverlapScript = transform.parent.GetComponent<preventOverlap> ();
						parentOverlapScript.setSelected (isSelected);
				}
	}

**Comment by mbinsfeld** [comment]
Here is the function setSelected now.

<pre><code>
public void setSelected(bool isSelected) {
        this.isSelected = isSelected;
        if (transform.parent == null) {
                        foreach (Transform child in transform) {
                                preventOverlap childOverlapScript = child.gameObject.GetComponent<preventOverlap> ();
                                if(childOverlapScript.getSelected() != isSelected)
                                    childOverlapScript.setSelected (isSelected);
                        }
                } else {
                        preventOverlap parentOverlapScript = transform.parent.GetComponent<preventOverlap> ();
                        parentOverlapScript.setSelected (isSelected);
                }
    }
</code></pre>
