### ISSUE TITLE
Board not being detected as full.

### ISSUE THREAD

**Issue by mbinsfeld** [mbinsfeld/Tetrace#7]
If I fill the grid as shown below the board is not detected as full.
![screen shot 2015-03-31 at 4 35 55 pm](https://cloud.githubusercontent.com/assets/3359000/6930854/5f40f7d6-d7c4-11e4-96c4-c4a220548e48.png)

**Comment by mbinsfeld** [comment]
This issue appears to be intermittent. Sometimes it is detected as full sometimes not.

**Comment by sptobey** [comment]
Does this happen in both scenes for you?  It only happens to me in the grid mechanics scene.

**Comment by mbinsfeld** [comment]
I was working in grid test.

sent from mobile.

**Comment by sptobey** [comment]
I think I know what the problem is.  It has to do with world space vs. local space.  The Grid stores transforms to keep track of the grid pieces.  I will try to fix it by creating an empty parent object.

**Comment by mbinsfeld** [comment]
Cool I wont have time to work on the game anymore until Thursday night.
Keep me posted yhough.

sent from mobile.

**Comment by sptobey** [comment]
The problem was that I was using a co-routine that didn't always tell the current truth of if the board was actually full.  And the message was only displayed when "Fire1" was released . Now, if the board is full and the debug lies, just click again, and it should say it's full.
